### ISSUE TITLE
Possibility to change path via environment variable

### ISSUE THREAD

**Issue by Nosmoht** [m1pl/semantic-release-helm#5]
Hello,

is it somehow possible to set the `path` configuration using an environment variable? I've multiple repositories with sometimes different paths to `Chart.yaml` and therefore need to switch it depending on in which repository i am.
 
Thanks in advance

**Comment by m1pl** [comment]
Hi @Nosmoht 
Trying to understand the issue. You have multiple repositories, so each one has it's own semantic-release config. Why can't you set the correct path for each individual repository?

**Comment by Nosmoht** [comment]
Hi @m1pl ,

thanks for your super fast response.

Seems like i totally misunderstood how to use the tool. ATM we have a single container image which contains the config and use it for all repos. I guess, thats the issue.

Thanks
