### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: with aggregate-error Version 4

### ISSUE THREAD

**Issue by Mario-F** [m1pl/semantic-release-helm#7]
The Version 2.0.0 upgrade in combination with node14 produces this error because of aggregate-error Version 4.

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/semantic-release-helm/node_modules/aggregate-error/index.js`

**Comment by m1pl** [comment]
Thanks for the report. I think I'll just downgrade aggregate-error for now. When I get some time I'll rewrite this and add tests to prevent this in the future.

**Comment by m1pl** [comment]
2.0.1 should be available shortly.
